added major, minor, patch version levels

diff --git a/.github/workflows/version_bump_pr.yml b/.github/workflows/version_bump_pr.yml
--- a/.github/workflows/version_bump_pr.yml
+++ b/.github/workflows/version_bump_pr.yml
@@ -2,6 +2,11 @@ name: Version Bump PR
 
 on:
   workflow_dispatch:
+    inputs:
+      bump_type:
+        description: 'Version Bump Type (major, minor, patch)'
+        required: true
+        default: 'minor'
 
 jobs:
   version_bump_pr:
@@ -16,7 +21,24 @@ jobs:
     - name: Bump version
       id: bump_version
       run: |
-        export NEW_VERSION=$(cat VERSION | awk -F. '{printf "%s.%d.0", $1, $2+1}')
+        BUMP_TYPE="${{ github.event.inputs.bump_type }}"
+        
+        case "$BUMP_TYPE" in
+          major)
+            NEW_VERSION=$(cat VERSION | awk -F. '{printf "%d.0.0", $1+1}')
+            ;;
+          minor)
+            NEW_VERSION=$(cat VERSION | awk -F. '{printf "%s.%d.0", $1, $2+1}')
+            ;;
+          patch)
+            NEW_VERSION=$(cat VERSION | awk -F. '{printf "%s.%s.%d", $1, $2, $3+1}')
+            ;;
+          *)
+            echo "Error: Invalid bump type"
+            exit 1
+            ;;
+        esac
+        
         echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
         echo $NEW_VERSION > VERSION
         sed -i "s/VERSION_STRING: Final = \"[0-9]*\.[0-9]*\.[0-9]*\"/VERSION_STRING: Final = \"$NEW_VERSION\"/" panther_analysis_tool/constants.py
